version: '3'
services:
  sonarqube-postgres:
    container_name: sonarqube-postgres
    image: postgres:15
    environment:
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarqube
      - POSTGRES_DB=sonarqube

  sonarqube:
    container_name: sonarqube
    image: sonarqube:lts-community
    pull_policy: always
    ports:
      -  "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube-postgres:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonarqube
      - SONAR_JDBC_PASSWORD=sonarqube
    volumes:
      - ./volumes/sonarqube/data:/opt/sonarqube/data
      - ./volumes/sonarqube/logs:/opt/sonarqube/logs
      - ./volumes/sonarqube/extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarqube-postgres
